import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { runCheckCommand } from '../src/cli/commands/check.js';
import { runFixCommand } from '../src/cli/commands/fix.js';
import { runInitCommand } from '../src/cli/commands/init.js';
import { runExplainCommand } from '../src/cli/commands/explain.js';
import { runRulesCommand } from '../src/cli/commands/rules.js';
import os from 'node:os';
import path from 'node:path';
import fsp from 'node:fs/promises';
import { fileExists } from '../src/utils/fs.js';

describe('CLI Commands Integration & Robustness', () => {
  it('runRulesCommand should execute successfully without filter', async () => {
    const code = await runRulesCommand();
    assert.equal(code, 0);
  });

  it('runRulesCommand should filter by category', async () => {
    const code = await runRulesCommand('security');
    assert.equal(code, 0);
  });

  it('runExplainCommand should return 0 for valid rule', async () => {
    const code = await runExplainCommand('sec-001');
    assert.equal(code, 0);
  });

  it('runExplainCommand should return 2 for non-existent rule (usage error)', async () => {
    const code = await runExplainCommand('non-existent-rule');
    assert.equal(code, 2);
  });

  it('runCheckCommand should return 2 for non-existent target directory', async () => {
    const code = await runCheckCommand('this-directory-does-not-exist-xyz123');
    assert.equal(code, 2);
  });

  it('runFixCommand should return 2 for non-existent target directory', async () => {
    const code = await runFixCommand('this-directory-does-not-exist-xyz123');
    assert.equal(code, 2);
  });

  it('runFixCommand should execute successfully on valid directory', async () => {
    const tmpDir = await fsp.mkdtemp(path.join(os.tmpdir(), 'repodoctor-fix-cmd-'));
    try {
      const code = await runFixCommand(tmpDir);
      assert.ok(code === 0 || code === 1);
      // Verify .gitattributes was generated by fixer
      assert.equal(await fileExists(path.join(tmpDir, '.gitattributes')), true);
    } finally {
      await fsp.rm(tmpDir, { recursive: true, force: true });
    }
  });

  it('runCheckCommand should support --fix and --strict flags', async () => {
    const tmpDir = await fsp.mkdtemp(path.join(os.tmpdir(), 'repodoctor-check-fix-'));
    try {
      const code = await runCheckCommand(tmpDir, { fix: true, strict: false });
      assert.ok(code === 0 || code === 1);
      assert.equal(await fileExists(path.join(tmpDir, '.gitattributes')), true);
    } finally {
      await fsp.rm(tmpDir, { recursive: true, force: true });
    }
  });

  it('runInitCommand should create .repodoctor.yml and return 0, and return 0 if already exists', async () => {
    const tmpDir = await fsp.mkdtemp(path.join(os.tmpdir(), 'repodoctor-init-test-'));
    try {
      const code1 = await runInitCommand(tmpDir);
      assert.equal(code1, 0);
      assert.equal(await fileExists(path.join(tmpDir, '.repodoctor.yml')), true);

      // Second run should detect existing file
      const code2 = await runInitCommand(tmpDir);
      assert.equal(code2, 0);
    } finally {
      await fsp.rm(tmpDir, { recursive: true, force: true });
    }
  });

  it('runCheckCommand should write output file when --output is provided', async () => {
    const tmpDir = await fsp.mkdtemp(path.join(os.tmpdir(), 'repodoctor-check-out-'));
    try {
      const outFile = path.join(tmpDir, 'report.json');
      const code = await runCheckCommand(tmpDir, { format: 'json', output: outFile });
      assert.ok(code === 0 || code === 1);
      assert.equal(await fileExists(outFile), true);
    } finally {
      await fsp.rm(tmpDir, { recursive: true, force: true });
    }
  });

  it('runCheckCommand should return 2 if output file write fails', async () => {
    const tmpDir = await fsp.mkdtemp(path.join(os.tmpdir(), 'repodoctor-check-out-fail-'));
    try {
      // Create a directory where the output file would be to force write failure
      const blockedPath = path.join(tmpDir, 'blocked_dir');
      await fsp.mkdir(blockedPath);

      // Attempt to write a file directly to the directory path
      const code = await runCheckCommand(tmpDir, { output: blockedPath });
      assert.equal(code, 2);
    } finally {
      await fsp.rm(tmpDir, { recursive: true, force: true });
    }
  });
});
