import path from 'node:path';
import { FixResult, RuleContext, RuleResult } from './types.js';
import { fileExists, readFileSafe, writeFileSafe } from '../utils/fs.js';

export async function applyRuleFixes(
  results: RuleResult[],
  context: RuleContext
): Promise<FixResult[]> {
  const fixResults: FixResult[] = [];
  const processedRules = new Set<string>();

  for (const res of results) {
    if (!res.fixable) continue;

    const key = `${res.ruleId}:${res.file || ''}`;
    if (processedRules.has(key)) continue;
    processedRules.add(key);

    switch (res.ruleId) {
      case 'git-001': {
        const filePath = path.join(context.rootDir, '.gitattributes');
        const content = '# Auto-generated by RepoDoctor\n* text=auto eol=lf\n';
        const ok = await writeFileSafe(filePath, content);
        fixResults.push({
          ruleId: 'git-001',
          fixed: ok,
          message: ok ? 'Created .gitattributes with EOL normalization' : 'Failed to write .gitattributes',
          file: '.gitattributes'
        });
        break;
      }

      case 'sec-003': {
        const filePath = path.join(context.rootDir, '.gitignore');
        let current = '';
        if (await fileExists(filePath)) {
          current = (await readFileSafe(filePath)) || '';
        }
        const needed = ['\n# Security ignores (added by RepoDoctor)', '.env', '.env.*', '*.key', '*.pem', 'credentials.json'];
        const toAdd = needed.filter(n => !current.includes(n));
        if (toAdd.length > 0) {
          const newContent = current + (current.endsWith('\n') ? '' : '\n') + toAdd.join('\n') + '\n';
          const ok = await writeFileSafe(filePath, newContent);
          fixResults.push({
            ruleId: 'sec-003',
            fixed: ok,
            message: ok ? 'Appended sensitive file ignore patterns to .gitignore' : 'Failed to update .gitignore',
            file: '.gitignore'
          });
        }
        break;
      }

      case 'oss-005': {
        const filePath = path.join(context.rootDir, 'SECURITY.md');
        if (!(await fileExists(filePath))) {
          const content = `# Security Policy

## Supported Versions

| Version | Supported          |
| ------- | ------------------ |
| 0.1.x   | :white_check_mark: |

## Reporting a Vulnerability

Please do **NOT** report security vulnerabilities via public GitHub issues.

To report a vulnerability, please email security concerns or open a private GitHub Security Advisory.
We appreciate your efforts to responsibly disclose findings and will respond within 48 hours.
`;
          const ok = await writeFileSafe(filePath, content);
          fixResults.push({
            ruleId: 'oss-005',
            fixed: ok,
            message: ok ? 'Created SECURITY.md vulnerability policy template' : 'Failed to create SECURITY.md',
            file: 'SECURITY.md'
          });
        }
        break;
      }

      case 'oss-007': {
        const filePath = path.join(context.rootDir, '.github', 'pull_request_template.md');
        if (!(await fileExists(filePath))) {
          const content = `## Description
<!-- Please include a summary of the change and which issue is fixed. -->

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
`;
          const ok = await writeFileSafe(filePath, content);
          fixResults.push({
            ruleId: 'oss-007',
            fixed: ok,
            message: ok ? 'Created .github/pull_request_template.md' : 'Failed to create PR template',
            file: '.github/pull_request_template.md'
          });
        }
        break;
      }

      case 'docker-002': {
        const filePath = path.join(context.rootDir, '.dockerignore');
        if (!(await fileExists(filePath))) {
          const content = `# Auto-generated by RepoDoctor
node_modules
.git
.env
.env.*
dist
coverage
npm-debug.log*
yarn-debug.log*
yarn-error.log*
`;
          const ok = await writeFileSafe(filePath, content);
          fixResults.push({
            ruleId: 'docker-002',
            fixed: ok,
            message: ok ? 'Created .dockerignore' : 'Failed to create .dockerignore',
            file: '.dockerignore'
          });
        }
        break;
      }

      default:
        // Rule does not have an automatic fixer
        break;
    }
  }

  return fixResults;
}
