import path from 'node:path';
import { FixResult, RuleContext, RuleResult } from './types.js';
import { fileExists, isPathInside, readFileSafe, writeFileSafe } from '../utils/fs.js';

export async function applyRuleFixes(
  results: RuleResult[],
  context: RuleContext
): Promise<FixResult[]> {
  const fixResults: FixResult[] = [];
  const processedRules = new Set<string>();

  for (const res of results) {
    if (!res.fixable) continue;

    const key = `${res.ruleId}:${res.file || ''}`;
    if (processedRules.has(key)) continue;
    processedRules.add(key);

    switch (res.ruleId) {
      case 'git-001': {
        const filePath = path.resolve(context.rootDir, '.gitattributes');
        if (!isPathInside(context.rootDir, filePath)) break;

        if (!(await fileExists(filePath))) {
          const content = '# Auto-generated by RepoDoctor\n* text=auto eol=lf\n';
          const ok = await writeFileSafe(filePath, content, context.rootDir);
          fixResults.push({
            ruleId: 'git-001',
            fixed: ok,
            message: ok ? 'Created .gitattributes with EOL normalization' : 'Failed to write .gitattributes',
            file: '.gitattributes'
          });
        }
        break;
      }

      case 'sec-003': {
        const filePath = path.resolve(context.rootDir, '.gitignore');
        if (!isPathInside(context.rootDir, filePath)) break;

        let current = '';
        if (await fileExists(filePath)) {
          current = (await readFileSafe(filePath, 10 * 1024 * 1024, context.rootDir)) || '';
        }

        const lines = current.split(/\r?\n/).map(l => l.trim());
        const missing: string[] = [];

        if (!lines.some(l => l === '.env' || l === '.env*' || l === '*.env')) missing.push('.env');
        if (!lines.some(l => l === '.env.*' || l === '.env.local')) missing.push('.env.*');
        if (!lines.some(l => l === '*.key')) missing.push('*.key');
        if (!lines.some(l => l === '*.pem')) missing.push('*.pem');
        if (!lines.some(l => l === 'credentials.json')) missing.push('credentials.json');

        if (missing.length > 0) {
          const header = lines.includes('# Security ignores (added by RepoDoctor)')
            ? ''
            : '\n# Security ignores (added by RepoDoctor)\n';
          const newContent = current + (current.endsWith('\n') || current.length === 0 ? '' : '\n') + header + missing.join('\n') + '\n';
          const ok = await writeFileSafe(filePath, newContent, context.rootDir);
          fixResults.push({
            ruleId: 'sec-003',
            fixed: ok,
            message: ok ? `Appended sensitive file ignore patterns (${missing.join(', ')}) to .gitignore` : 'Failed to update .gitignore',
            file: '.gitignore'
          });
        }
        break;
      }

      case 'oss-003': {
        const filePath = path.resolve(context.rootDir, 'CONTRIBUTING.md');
        if (!isPathInside(context.rootDir, filePath)) break;

        if (!(await fileExists(filePath))) {
          const content = `# Contributing Guide

Thank you for considering contributing to this project!

## Development Setup

1. Fork and clone the repository.
2. Install dependencies: \`npm install\` (or your package manager equivalent).
3. Run the test suite: \`npm test\`.

## Pull Request Guidelines

- Ensure all existing and new tests pass.
- Write clear commit messages and describe your changes in the PR description.
- Follow the project code formatting guidelines.
`;
          const ok = await writeFileSafe(filePath, content, context.rootDir);
          fixResults.push({
            ruleId: 'oss-003',
            fixed: ok,
            message: ok ? 'Created CONTRIBUTING.md guide template' : 'Failed to create CONTRIBUTING.md',
            file: 'CONTRIBUTING.md'
          });
        }
        break;
      }

      case 'oss-004': {
        const filePath = path.resolve(context.rootDir, 'CODE_OF_CONDUCT.md');
        if (!isPathInside(context.rootDir, filePath)) break;

        if (!(await fileExists(filePath))) {
          const content = `# Contributor Covenant Code of Conduct

## Our Pledge
We as members, contributors, and leaders pledge to make participation in our community a harassment-free experience for everyone.

## Our Standards
Examples of positive behavior include being respectful, accepting constructive feedback, and focusing on what is best for the community.

## Enforcement
Instances of abusive, harassing, or otherwise unacceptable behavior may be reported to the project maintainers.
`;
          const ok = await writeFileSafe(filePath, content, context.rootDir);
          fixResults.push({
            ruleId: 'oss-004',
            fixed: ok,
            message: ok ? 'Created CODE_OF_CONDUCT.md template' : 'Failed to create CODE_OF_CONDUCT.md',
            file: 'CODE_OF_CONDUCT.md'
          });
        }
        break;
      }

      case 'oss-005': {
        const filePath = path.resolve(context.rootDir, 'SECURITY.md');
        if (!isPathInside(context.rootDir, filePath)) break;

        if (!(await fileExists(filePath))) {
          const content = `# Security Policy

## Supported Versions

| Version | Supported          |
| ------- | ------------------ |
| 0.1.x   | :white_check_mark: |

## Reporting a Vulnerability

Please do **NOT** report security vulnerabilities via public GitHub issues.

To report a vulnerability, please open a private GitHub Security Advisory or email the maintainers directly.
We will acknowledge receipt within 48 hours and work on a prompt patch.
`;
          const ok = await writeFileSafe(filePath, content, context.rootDir);
          fixResults.push({
            ruleId: 'oss-005',
            fixed: ok,
            message: ok ? 'Created SECURITY.md vulnerability policy template' : 'Failed to create SECURITY.md',
            file: 'SECURITY.md'
          });
        }
        break;
      }

      case 'oss-006': {
        const bugReportPath = path.resolve(context.rootDir, '.github', 'ISSUE_TEMPLATE', 'bug_report.yml');
        const featurePath = path.resolve(context.rootDir, '.github', 'ISSUE_TEMPLATE', 'feature_request.yml');
        if (!isPathInside(context.rootDir, bugReportPath)) break;

        if (!(await fileExists(bugReportPath))) {
          const bugReportContent = `name: 🐛 Bug Report
description: File a bug report or unexpected behavior
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the issue.
    validations:
      required: true
`;
          const featureContent = `name: 💡 Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: Feature Description
      description: Describe the proposed feature and why it is needed.
    validations:
      required: true
`;
          const ok1 = await writeFileSafe(bugReportPath, bugReportContent, context.rootDir);
          const ok2 = await writeFileSafe(featurePath, featureContent, context.rootDir);
          fixResults.push({
            ruleId: 'oss-006',
            fixed: ok1 && ok2,
            message: ok1 && ok2 ? 'Created GitHub Issue templates' : 'Failed to create Issue templates',
            file: '.github/ISSUE_TEMPLATE/'
          });
        }
        break;
      }

      case 'oss-007': {
        const filePath = path.resolve(context.rootDir, '.github', 'pull_request_template.md');
        if (!isPathInside(context.rootDir, filePath)) break;

        if (!(await fileExists(filePath))) {
          const content = `## Description
<!-- Please include a summary of the change and which issue is fixed. -->

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change
- [ ] Documentation update

## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have added tests that prove my fix is effective
- [ ] All tests pass locally
`;
          const ok = await writeFileSafe(filePath, content, context.rootDir);
          fixResults.push({
            ruleId: 'oss-007',
            fixed: ok,
            message: ok ? 'Created .github/pull_request_template.md' : 'Failed to create PR template',
            file: '.github/pull_request_template.md'
          });
        }
        break;
      }

      case 'docker-002': {
        const filePath = path.resolve(context.rootDir, '.dockerignore');
        if (!isPathInside(context.rootDir, filePath)) break;

        if (!(await fileExists(filePath))) {
          const content = `# Auto-generated by RepoDoctor
node_modules
.git
.env
.env.*
dist
coverage
npm-debug.log*
yarn-debug.log*
yarn-error.log*
`;
          const ok = await writeFileSafe(filePath, content, context.rootDir);
          fixResults.push({
            ruleId: 'docker-002',
            fixed: ok,
            message: ok ? 'Created .dockerignore' : 'Failed to create .dockerignore',
            file: '.dockerignore'
          });
        }
        break;
      }

      default:
        break;
    }
  }

  return fixResults;
}
